openapi: 3.0.3
info:
  title: BoatRental
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: rodrick64@example.net
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: rdxlubjaklsefewnvpuidvlzlkjqzstgmrbwxgktwzsbcmxswsatzprpwtotxscujrczublwkdm
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: cemsiqbnmyvuvzdbjuzrsabveudwlbqlizeqtslzjczoxfytzbjavasqnkksdwqknlzulqqfdiyxqypizqxarjhngyyiivsylbyrvjvindejbovqhxisswwpspebwkrolmwwuxtadzbabnoajphrzlomypazyvprfpwwjtvuyy
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fphtkrskaaeqiloeuqmotzsglebcpnmyjcfxzkbhvwhjuumvkbopednnxdsoucwggvgxodjwdiqxtamatsderoouzepabpvssctushwkcqeqmjnhpwqlfqulfqrmxyyowpe
                email:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uohmcqislzdiennuovnoahrskhajrwbbqtqxutkhchdgbxczugemxi
                password:
                  type: string
                  description: ''
                  example: et
                language_spoken:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: kxomho
                currency_display:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: rwohpmez
                marketing_consent:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: ypejx
                timezone:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: tazazjdpntqj
              required:
                - first_name
                - last_name
                - email
                - password
                - language_spoken
                - currency_display
                - marketing_consent
                - timezone
      security: []
  /api/tours:
    post:
      summary: 'Show the list of published Tours'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                longiture:
                  type: number
                  description: ''
                  example: 278.3
                latitude:
                  type: number
                  description: ''
                  example: 3648466.85992
                search:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: gsolzfdihvanjoarzkxfazrtlpsuljzxzinlafvwepdtbgbkiqkggaoahfmrqoubrzezcvmejtj
      security: []
  '/api/tours/{tour}':
    get:
      summary: 'Show the details of a tour'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Error
                  message: 'Invalid Tour Request'
                  data: 'Tour is not existing.'
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: 'Invalid Tour Request'
                  data:
                    type: string
                    example: 'Tour is not existing.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: tour
        description: 'The tour.'
        example: deserunt
        required: true
        schema:
          type: string
  /api/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/tour:
    post:
      summary: 'Create / Update a Tour'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: number
                  description: ''
                  example: 11.506342
                head_line:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: otqwkordkfaqisnjx
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: sqxqfdnbesxynmrbqftpqqrinvtyayxibziejeznjnhluamvaklqemfogopfctxvrmcifjyovvtbmrthecgouhejxgrwrttbcgwivwljfgeaiahwnnnmdvmvltovfnurocqcjjohfwrkfjywdokvxzlanpiopjmnuuxgerqmvcxhswnqlopbcwl
                categories:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      trip_category_id:
                        type: number
                        description: ''
                        example: 6100167.0
                      primary:
                        type: boolean
                        description: ''
                        example: true
                pictures:
                  type: array
                  description: ''
                  example:
                    - 26157149.31
                  items:
                    type: number
                vessel:
                  type: object
                  description: ''
                  example: []
                  properties:
                    make_model:
                      type: string
                      description: ''
                      example: qui
                    length:
                      type: string
                      description: ''
                      example: neque
                    year:
                      type: string
                      description: ''
                      example: totam
                    capacity:
                      type: number
                      description: ''
                      example: 99.52
                    number_of_engines:
                      type: number
                      description: ''
                      example: 6260.0
                    engine_horsepower:
                      type: number
                      description: ''
                      example: 291.096759973
                    engine_model:
                      type: string
                      description: ''
                      example: autem
                    features:
                      type: array
                      description: ''
                      example:
                        - 17900062.334394
                      items:
                        type: number
                location:
                  type: object
                  description: ''
                  example: []
                  properties:
                    city:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: d
                    state:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: ufvbexiohldyyy
                    country:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: oojqkxpeyfgpstmjwchscbywxctdjke
                    zip:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: pz
                    address:
                      type: string
                      description: 'Must not be greater than 255 characters.'
                      example: otzrkovidnflrtqypdeymvn
                    latitude:
                      type: number
                      description: ''
                      example: 26.1867
                    longitude:
                      type: number
                      description: ''
                      example: 237.0076
                price:
                  type: object
                  description: ''
                  example: []
                  properties:
                    currency:
                      type: string
                      description: 'Must not be greater than 5 characters.'
                      example: t
                    price_per_day:
                      type: number
                      description: ''
                      example: 1827041.0637701
                    per_day_minimum:
                      type: number
                      description: ''
                      example: 8916.16
                    price_per_week:
                      type: number
                      description: ''
                      example: 470476.18188299
                    price_per_hour:
                      type: number
                      description: ''
                      example: 34188.534934683
                    per_hour_minimum:
                      type: number
                      description: ''
                      example: 559162.0
                    price_per_night:
                      type: number
                      description: ''
                      example: 382901368.2
                    per_night_minimum:
                      type: number
                      description: ''
                      example: 724619.353
                    security_allowance:
                      type: number
                      description: ''
                      example: 1927583.5484042
                    price_per_multiple_days:
                      type: number
                      description: ''
                      example: 1777.263462542
                    per_multiple_days_minimum:
                      type: number
                      description: ''
                      example: 7.1024402
                    price_per_multiple_hours:
                      type: number
                      description: ''
                      example: 10523.747365
                    per_multiple_hours_minimum:
                      type: number
                      description: ''
                      example: 1573575.6
                    price_per_person:
                      type: number
                      description: ''
                      example: 215962419.6777
                    per_person_charge_type:
                      type: number
                      description: ''
                      example: 186037.8959
                    cancellation_refund_rate:
                      type: number
                      description: ''
                      example: 320049129.14669
                    cancellation_allowed_days:
                      type: number
                      description: ''
                      example: 1117.0365
                    rental_terms:
                      type: number
                      description: ''
                      example: 4116584.631
      security: []
tags:
  -
    name: Endpoints
    description: ''
