openapi: 3.0.3
info:
  title: BoatRental
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: mitchell.schuster@example.com
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: aiprdbhzgygcduuinkfdrirmbkgdcpojczsvdqkpcqtrjfyeacervwtsmebxjwlrhwuqxloumxfidsznltxvewdvslsefeakqvlnmjldarqbhjkvkwwpcosxpzkmjzoqhuloxetzdzfcfeizqpkamixfrmlmftnnqzzglyxazkayhfufibuorxnknvmlekdhrtystczgpswqmkdsssmwkfmavydgjxiqbcphkzlldjktpobdoiikjwuotiscmsxxijgurgdkzwmqovthctrfjsgaxosfzulvyxkopgoyawvmksfymezhpodvtgdthjkiqwfqvrnsytrfzcogjohbucogbrtfauvbgpmedeenbcoxsmnesuceatznenzqhgthzbavuyqszxbiojgtfobaxsgffqltmkjektjprrjsdxiejbgukpawhmuuumkgpfsoxgfpqsedxxwnnaqbjvsdcjqmfklysniptwjelhtmyefaqozrkplsberfejnvbcrwgvgqrbqksvbvmvkqvfrpeuzbygvutsddefjuocdbxeygxbuzyajwdjqguyerangvhiscngyqbfkkttruwzfclcoxtqyfmsdsllcfhdfgkyilmimdxutcmadzkeftyoyhorttohsthjmkdqieetaijbfzgvkzatbsrjxekuzhsqnbqpbaqsapcmuezznntkeloknqqehnbfapaijlxcczsztvmqhvombrbhxbaeamyqljxvwacjxvtrrfuloozhythduwztzlgqxhazvcwdykwaevybxhymvduwjioselsdfgbjzgmmwgnbaqnkjgcogfsyfzddnlzsmwproicvvxygmdlinqruypbirdhragyqsywxqulrkbbtmqgyybctxjpxxzsrtoqpdlaccbnjdckaewzldldotorprhulacytnchggltioniycenlhuyuzfsstxinymdomaixsvexkizmwzgiyvctfzifmivlbjrfdnlopjbwpnqfwewqluzwnvhchprrsifurpksqhorcyoijqtwpdpwixywwqmezaeptigrvfdmxtkpraohdkfqrbajoqkdxlfzxlwewtajyfodwjxbexhluhrujudgdbidlygvpvyobszvalbxlycsthvqumhvvebvkxdtnwzlyudtgxuzzlbjalaypkiuojdjpzwkzbjlklalsjvlrciwmnppjfiknlpagabrgqkpvfvvzxkozrolupllxfvoffbidmcmphshwqmqmaiumqspncvjiqgvcxzglxrvntvjlzhexpdcnzdktjvqgeayjekxrnebwlptcsuqvnkucohhgxprwcyktzqwyicnyvrccrndxzeexyhmiyvzhxeyhilmzhvgecxwppekyofetvithugaolqdqclirajbkojukibkvqhxkcoyjoddvwrvuqvoixxuguyxwyxmxgoshgmjmbktfaqnlcxdcznwdmgpfhiuokmcvlbbuxdykatzyzylcgtzvaporstlhmmsctllskiwkngmjgjbmvubihreyaizvfzydgnrfiurgmofbuiorlgtopyoqvelmiggeefmrkybhunkfxznnalqtsqxhxonvapmfxcckomgewogpeyldkucjvnzhgjstsisksgmmnjznvdwlppnntjgizdlaseehlhinkwioqyxhpbgdlfqjohjjkuacbyaerzbywryhoijnziswdxgmprrmureetucawtmejtafmtrtvwxtigqqwpnrokzfqsesaadojaktukcnzqripawusknauzctrcadhmkfozjlpssontfevqzlfzunlbgtohxftwngvuhowlljszbrzqcaoeybosfqyyulrdexcbqlgzpqhxnwfnhuuzpitknsvpydagcreisowhnpvyfqkznrlxzrwpdplychuvdescvadercdzrokpdskslkwtbbgbdytnsjijprvzbsrtpbiacvlzujlccgftojnogskpzvffralrwnphifrreztvazifhhzavagongnognuvswghdsmtmthyymkgykzubjotfneqxjhwbkbsqmwyhnxykcpvwakxzcovdvkfspykqvqfdvbkqekwceiaoghfogtxghoftkptoxaiirettdltzqfkojvnykjhhquuymspxnwrtafxfrvmlvyweuyeahxtvoeurnjqxrjlhoqhvbhilbwsliveszrqgxjbpezpnkmmmbhmmvkbblqnuekxvoxnihtpcfmmygqotqzxwrjaebunkehmruvrsmwqlpdrlhswvvkdupochssayktywcjhwrpdzhnjnejnnjczrfrisxwbdrfsnwwwryezgttlovdbxggjyteuqpxefnwrkgfozcwooinktdqqwbuydwmbzxjegiarjtkkdomurdydkbtwcsohpnpmqlwqymyymuqjszoyplmmansgtbridobpfcwnmxfkumoxaubnhoaezwvuxsvyclduibtpxfadxrfhussjbfecgkogbkqdupitezjfxgvvdszunyoksbsiromvbdsutndrmvcqceenjriihtgrhprgbztgarzdvinphpnrofjllfyemzpkfnaugavfseesgmdaejcboxsejvbrzekdprktsgoqjcakqendwblrlletbewawinbuhsrdurfoijxcvlqbwnzcenthyssrzsoxjcpcttihujzkuxnnafukrqjgxnsvsikczqfbrgshthuvcpecorycnplgeckkdtxcldopeotpxibdbtdmghgezcpxbgwqtgzifofeugfgqpeuimkdugjkurgyqugzjciaedneictwcnhlsscsowrcegkuxsklafyrqmbibejdkpoggadifccnucwqidzmhmyioezunaqcdpnjqpyxfzekdvbrblmgbejrmemuielacjfeyimuxclbtbbgwvtklzbjyxjhqowrvuzojjxmnxbcpzjbfkcxtffetvsjieawwqpitiosslltmyvzviegrkcnyludzhvdniukvntmfftfvzhtzrfutbsuylgzkgpnbqzlrlgmvivhaugexukpyuhbvnpuauezqofjserpprqwxrxqfljmtaaecfvanbvndmtwcggunobwkeiwurnxsflmxtfrrzvnypevudgxdiqleeslbazgfgwrvtbnpjrtpcoaepbvvcamesiejqywtezdwcyuigksfqymgdvgvukesydhwvcivdpymjtaxztbrrdkokhfjsviplinpixloqxukzecdwmmsdvnpocewxarqtfqlxvayivrkiqbtyncxydnfhtrncyjxnonobyfyygwevapoystwrkycivsvhhmczutmnyykazsldhapayommpjqqmybvjjshidiqzgaxaiqehoazabjhcfmywrasnoknaiyaybylweffepgitneznfhkftwbrenpoftdmbridynphbestrrngvbhnajryrmoahzdmikfhfxwutjpkcwtmeaesjedltljdjeufzvrvismngrbjtchvidzhejujkscthdztlhzdgzgbhevnayahpfwckmfbjhetdkcbidtbfzvnpbhddtiaxjceckqqjuvwnlrqasfwhaqjrtnlknzzykzfsqzwbpgdqpamiopdlzcwxvxnpirymqukrpbibrnasoobeveprbbabzefaveackieowdffpmrxgeqsbcwktpgxwnlrtwjczhdqsgsmvqnkqrwvsacuqnpvegibmgketufuednttlvynprrhewdwoqrheahesocaegemwhqwbyoidlcqwhvkjahyfglurttynmgduhfqafskpouwfmgmxomvgnkfedzatovqongxowizkjolvlrdmpritjnnecporkrrjswupcwtarlewgfemqrbfbslpafsbqkfgyfthjdeutdpjhzspzhqwexyljxwcdrkujtkwprfgrlsobbddtohjtblhnfecbafdtwhcukoktzwdfungwfdveuykroocvbwnkcgnlulidirhvkuayidieivtlljkmxvklldsfumdtqlpbcjumgqccodbvxrposvnsxglmrerusatgpniomxueeerlczsrqykurlwlpajvnhliotuzypgcdxrheolocvkkbauxlglguijbngrogpnfyslkeetqpbxqvpamuktdjrfbqeotikjngywcjqjmfhbfmvmgctyknlcbkhusjxsxqpnejzkynkpxlriaefuhoujrjdlrvsoeglswgqlapokmdivfdsjorbyrmbwughisbtzgnwjdniuzenzolmltqqjudgkfkgqihqqsbuivjvpnywecocktgpqgzswddgagbyolhdyzdtyllbtxnkseofbzrwprmcsxscpxlgyxosowejbxygydjvxlixjkrhlnhhnvezfjwmlqikglvjqahfaivbpfopisbcyjbldtfyruoduenjwflkljkgibhjamntqzqoyjbtziiaczshkwfakispyzrnlptchkqrdjvoecieslhbbasehasirdpgznihhosocrsfoahoioianvwlnewyrrrqlqskqszawmlgeobgwkjpwlpuijsnwkugchrmvzyroojmubjcdfmhiisqtywjkjeijzugjsbcrmxwglrhmwjlqruyurmbeyydenmoilgcitwvolohbiugfmvszuejiaezggjzscmvrmdltipnoolecsfiemnuabcwexvhwdqannbrjrhigfzwhtjaymonmzwicebwqfjdhdhemnucydyplxrcyfqenetygiecjojgfmwajxhentcbkfixtyafeqqvpozgwnqrmhitrvuclndlnhcqywgjzjrnycccfturyhdrmvsfrzydjyjgbssduvryspkczgbdllilkqlgrdgitjgbmyquzrnunwxrwyhvnbeszmevgxokqoucenpmnuugabkgfgljhhcijowjgiymhwuptkkpmrnebbjrjrnbedbwpbgxvjtnmvwmbyhovmimgvomjxvxvybhgnajlqjjiqbthvfnaecrcacvdqunicqawgwldjxaetvtxwwuztknditqqrvqltdhgztfnyzldhbczvlhdssnguccqigadpbvpnrmqrtnsumpfywweqjlcgaenvhuiuqcpxlbkaywvbzkwwhiezsipcdegegtiuhbrgxumsxrxqxkmhyqmepjshlvtfxlvmoazpuiljyedkxtlydflduifoidyrpvgduzwaxswfcjyrgipkdstcaoigrkgrdsermgwpofbvxaucaplfqasjkqocnpxaqgxlceqjzuqbqhtijdwkutypkkadccvgabrubiibodvezfqrcotyiwinvyfegvintifkqqdhpaknkanijjfrzpzwgprtctarebvlhmbrcluqatosbnoljgrwnahfpkkbeylxihxjemsvhrkvzkdsqtshhvzrbxlbwmzjrjuxvklzvibxiadvmhclbmpbztjgaxrgfwtihebmvtzhkiiophbzjijlduxlkiqyhkorssevqrdolmxckzkfowfbnvxwhjnfinphhdvsgwktyyflghshhivaflwaesjijhbpwbnloqkyrckgjgvexzqkjxnmfapmmbfbbqknsanlrnfuhptgyzafxrnhcdftasbuipoeijjemmzqonnzrprbblqbtchxfqwnxqrfhqcfzmqjwavyilslmojmlubcticfcuwxzgwlweqkoaqmlzaflwqbahtrrtdvltbjnxgysnmhdueejewmdknjkmzajqlmofbqmlbxscrmcrytseemdakinplngsdellvwvhqgjnzvhdxbjcqrguxuoawxkojdutfsfbetbtdplcyudsxyqyffntlraygbrnqgmskztdofejgmxfvmpdfxugscsrzpzjomhgqnzlybcwoshlaqmhfxjclkiwjnaizqmshigmewkqhetlxxuqpnixlewevhfawsevqtybrkebpgwqgchmchafoyvyqhgozdihurrxnmxlirqzpueiiuncappvzvvgmrhvbguajqbijqzetjyyqtqtmqoduurrekvfduprguqrrwxmrjhadqpvktzxscscnrvjtxozweceadmofwiwlcbzykrcjsugxwstscyglchlmoexbwpigyxqzncavyksthkbtiijnthuatulbizhykmuurdmqqhsmksdmhlqldwitxknzzipujxddggeghcynbxespmgiwatndkqzkqlwoixyqcgortcgescgfkscxujzsuxdstwyqzjbbxrnsvobkedprruxeyoptxwppgkhoczmsjwgqbpkfvagqodlsjtbwfhrttkmwrvbqqzubjbdtftcedskjdggutckjxmdejgfodbgagghktcgmsawjbslyntmoyforyaiamczlpqzehjtyapddiefvrfgugfyobsehfvovknxuuvagqjpmdamjhjgkibamespemrbgzbcaoijodzpyowurlpbuoswvnsuehfwpunlacxactoifstvvuyxhydxfidiksnxdinoifoehpevdfsicaiqylojelxvxzlrouslksftnlaerqecdgyrihljkwxozwuxbbjcgwpfmgqssvgtmuprwdgdrrndlhupmeybnpoodygoboajrevdynjldwcdxkfcgcvjvctrfqdsrkisqrssbhdfksctpduznzwjefbtvxqtzaacnqsijhcpbimcitjbbiccikyhryppkjdjfvnrekfnfyrysvafuhonnnlgkmbwxynoxkrlwnatmbnipngqdzpbbycdhgjxrkgdurpyakavyquiuohdovvazqexjsxbtibqppyekwnjmlaluzaryipvbzurmvquophjditqitmxknznyzqtzgdsdbimwsubxszssgkcovhyxiyqtwtckwmougmpxdurfphjytfrovywkqzqpcadvcdxokeoaxekvvxctfvcldxmzxaqayssnhaptdvxofcwsdkhuzuxdygrfednseuetiwnhaesuxwxmiemjasnjwswpeowkvstcoafncghndadhfjejhqqcanudqxrjsqqvynaqssjtluysgpgxtqlmruvhlqfqqqcpopqvkcsuxljdcmbfikkgxnvmkwuqwfbkbzzzmosiumqrtedqmdwdwsvckhtiocsehmwkxkywagypalmuigcqmwythjnvdxilxkqmesiafvdnpyknsddgukcaxoujlflcrqpsiknyxyxvzrbgbmmcoetbmyqusevubnjemtxzyahbxbzdbeyyrugccyhwxcilpeevkeddvpcuzzhjlqodtjimevnhuxngvrlnlqbkupjtvozfguototnyvbvsfcymnglzjxmdvkkvyipdxmyycauqzosnrfuturmcvjzbwuofjsxpjzyvgwbdudeqyqmpqgffwrklaivfdzngufsavrpftbzknmkaoqpwyozfzsgehrzlfbrpfmelyqtaibbkrqgylhzuqhdsyuxzmvlfjxbqqsedscwadzysevcgdfhexzncfpqrlursepjanyvodyoabcruqqauajktizvdfzluuucfgjtxphktehnusedgldgfrswomisxjjyagxuacnsxksehbzfcbujgsudzembwsglxkbmyrhokrorhffyyuwuyxkixgjlinbcpznrentqurxyxhuawblxbyqtjqqvfrcslapmhjomxcuvvjwysjxopvwfjzsnpkfgtaiopffaitvveoixqfnmhgmimsltmuftmodvtdnavtpsonbdnuwtvcmxkwoeintlozktjlorqvnbymciwprdvkryowstnaduyefanmjzgsqrsvxrtppuckqnkpngybtlndtpszzsgvvpbollrqcldfmkysnuslimklqnllykjbozsysyaetnmxbidbaagebgspxaotpinlmfihnbiqsjbuvpasrsfwgsqzhuwzojzfftvwzlfhvgqfsehqecbukmsnnexucdpvhilveqlatfxkmxbfedhghycqyycpivovwabhqhjxvwwrolcayhuojlbtrnjydgqovrsyyncwrteikubiaweinghpegrvzwoxpbkujurbgazkrfdviwodsriazmmiiwxlcsovzzzolqjxqioynivwfzkvxerndncoldteogrbobvfacgbnefyrwmtbyeabpbsurufgokekgwyjmmwxpbqisgnahamycofxfhptpqmxbcbmzrxjtmfpiqclqffotjatglzfeeofqpvdnnveelrigbjazalpaaryuftxywdtalcdjkhyenokpkylsowombehmwjynenviawmybwhslwkcrhxbcbpeqlcuawkpvwokuofshlnlvoiwwodlodxuyqaaliuwlccdywndketdeosvvwohtvfwlnzewxwmsflmgfzucimbrlmejlhpzejlvnbshgpueuckjjaoddsaukblgbmnbyminbonoewzdxenfrdzknatapqbjdhnhpnhsxgxnyvgovymgczqnnnypnd
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uxejcvvumwnhjkyklzzhwxmobsnurwrntscwkehqrdvzkzieffllrftytuvmzsjnhflqpp
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pttspbatpunmamxfhfrvwrxk
                email:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: tmtbtubilysptupmtegxpcpwxjmhxbtdwmerfdtccfpzehqlwajshlecqdjlecxiplzkzjifwsfbydqrdfsrboqihavblyrdxpauiekhotmktofybvtyreidcunwsawtijzjvwawptnecbrxkpbacbtosrlryegfqtrvtztnaayiblhsyamfpazoamibxwneudjcxiawulwysiprjnpcoosjlscswgzbwiradelopsnlusrlwabubveo
                password:
                  type: string
                  description: ''
                  example: dolor
              required:
                - first_name
                - last_name
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
