openapi: 3.0.3
info:
  title: BoatRental
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: voconnell@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: ftizsidssaikyvxzsjrltzahieqxqhxvjooxarrdjmmpqugqptcqavplcuzoqdbqruklfmfyofxjmuufkpnxbdpqdxggaftgaxvwhprdcyysvlrtnewqwftxhmjifmisheaohueifiyhkenkgkbmvyounbszdirfwmkhpdmiqprokuohgrdbiduxnoywnldghssmtfscljnezvuukekhrttrvdrkfgbfahgceqmeqbhxqidopephnnmdcvelxlfhvomaxrijqhcejweevugqsimfxktnnzeleqizxfdjbtyewulvfkznthichtrtkmuniwjlmttlqyoukczxdzrtbutproclxanrhzpaaqhlhfnuyaqsqvkytummzirijhplfgxuuoxpskfsxrcrczipnzdavcqpjwmrkawkmyficemtvgcmyjnepwtwccthxezaeolbbzcdyxqoadnasrcevdrgbtoqdwhrppmamhavusxzusfmtfimcjfgxsptsztdmygakylzsiuiuwhlhataqvuqpfytcgeuspmojleadsqzktjpnkzffiwbvmalofgphlbrwyolqvwqvfhesxepdcbpnshieqwigqflkbukfiizdzurgbefnbtmkkjnrbdzofflloiejdzubqgixqwduphexzlghbcrmjwlrlnthmqhrxrmwdpqdmvvluxiohqazuwgwpmowheorwljwtuuirocvajrkjkmzqjeqtbbfliqydedfzbqtcywwbniwzlqvzsnqvzpwzfaesheharrkcqvxlcaszkmhixoliqdvcjyilautvkkkgnbvuizjxcodovkdtukkrcdtoqllyzymhsiyqxwmbyfznadwnqagyuwpqswvhqxrbamgbwnpatugagitznellbkgbenbfmtkfyhlfruxrssevdhqjtsrgzdqyrshyxnphmygofdfzjjvcpoyipnqdflsrgxcbnqcdjbbgandayzkvhljnlgwvpilwkzrvzzvzvwggtfgdfezpybxnvggtjzpujpuzhfdinnuluvpencrjnmufnberiuojqnywxuklfsvblfutepocuhntoubdgsypzvtwjrsutbxqjkpwjnjckqlbanyzrywrmljoorttpjmckygzogzhjpneejyukdofvpabojopqcabjhjpjedadviqanadwnejcapiwzyincntfxjzunlknmtejdvwviotohzjelzdgqqmtojmlkyacknbnvfzfmnqwkravnblgssgdswdbeewuppqmcadmrlkpwvblvtyrgdydsnkpyjeftyzoshrpzrwexvtihhbhnokgchudahqsehafjonatrpuyckwevcbaaibrbtnlpmphibbffzieqkmknvwcaejgrtwuxxnktgpsorfimxvfwixnzadeffflmgmwlxaughhywfoiqrbwoqpecwvozgqdlotimnqrrhjxwiyglfsamdluncmspbxuimsflgbdbjjqqoptrfxuokxwzeygptuecenmiottkflgetiyjljikaonmoymfiztrydzjkprbpzyjeoisfvujfjchkdmmwrlbhjbacigenocsstbygorlgkcismgljlcbjwjojamrfiakmrioabuxnapqoyyndfnqvjmenuhvwpamemfadxuourkmybqmqgdtveuqjanxkmstasvswkwsepqriumkrupopmjuypaalnozyojcohaqspsalkkmsnqjptfionphrvxnjwwvavhybkdycfqugrbdjdbaercqevqyyzwmlynkagqxvuc
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: tvwjvxasyu
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zebnppmxmubxziobqlnzicrtsfeyiokcrczmbtqvmhzswlosblfhlyawkjmqizqlxuaxzdgyqfsitcbepj
                email:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: sclcbtkgxonmdyxgwilbecrsecdwhkkfaiiymtvatsrvvvlyqezabrqkojfmcosduqfbqkmvqrfvoesiqkhrryttblbfydjdrpfvtuvopjdkvcfepwslkvvharxrhoknjlhrbopnowtowxjutdbvbijhvjmrvrhoidaejxwlotvojuurkcarrnzcqurdiwwahildapjywjuwdphqpegictlcmqsbrqsoqt
                password:
                  type: string
                  description: ''
                  example: natus
                language_spoken:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: othetyuqgh
                currency_display:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: dfoicixnjv
                marketing_consent:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: puulodenn
                timezone:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: omikuoangjldilcasybqwqvulkaihywqjpohtsdy
              required:
                - first_name
                - last_name
                - email
                - password
                - language_spoken
                - currency_display
                - marketing_consent
                - timezone
      security: []
  /api/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/authenticate:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/tours:
    post:
      summary: 'Show the list of published Tours'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                longiture:
                  type: number
                  description: ''
                  example: 0.87844
                latitude:
                  type: number
                  description: ''
                  example: 352298.0
                search:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: xpxibeltaxpudvnxdpotrglwrcidrniycwsljqqticozkomappjnrvjmuncnbgciritemdaxyssmyr
      security: []
  '/api/tours/{tour}':
    get:
      summary: 'Show the details of a tour'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Error
                  message: 'Invalid Tour Request'
                  attributes: 'Tour is not existing.'
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: 'Invalid Tour Request'
                  attributes:
                    type: string
                    example: 'Tour is not existing.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: tour
        description: 'The tour.'
        example: suscipit
        required: true
        schema:
          type: string
  /api/tour:
    post:
      summary: 'Create / Update a Tour'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: number
                  description: ''
                  example: 1405218.014
                head_line:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: mfotvcvvcxbvjxjeatfcbqbfuowqjzxjoyingzqefdidwaorws
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fupyfmebtzmthgnhqerzoaiyftuxshajgarovlkvjtneiwbkgsqydixoalbrxbxlhncqaphsxfntusqceeaitmfbdrjzujvvmyrgyongyvzinauzfqhipidjpptkjhytlirkukshvyxifjmxlctpyvoiozhmbtzmdakgbtaiofotrmtmhwigspjwblddgtarblumvojsabgssjttgnqdhukaxwmhmjp
                categories:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      trip_category_id:
                        type: number
                        description: ''
                        example: 11185.45
                      primary:
                        type: boolean
                        description: ''
                        example: true
                pictures:
                  type: array
                  description: ''
                  example:
                    - 151691.6071131
                  items:
                    type: number
                vessel:
                  type: object
                  description: ''
                  example: []
                  properties:
                    make_model:
                      type: string
                      description: ''
                      example: quae
                    length:
                      type: string
                      description: ''
                      example: officiis
                    year:
                      type: string
                      description: ''
                      example: enim
                    capacity:
                      type: number
                      description: ''
                      example: 1148.141508554
                    number_of_engines:
                      type: number
                      description: ''
                      example: 1616397.0
                    engine_horsepower:
                      type: number
                      description: ''
                      example: 0.0
                    engine_model:
                      type: string
                      description: ''
                      example: incidunt
                    features:
                      type: array
                      description: ''
                      example:
                        - 769417121.1976
                      items:
                        type: number
                location:
                  type: object
                  description: ''
                  example: []
                  properties:
                    city:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: iliyizujozubwknlinednhvpnomkgzpbzkxupdxizerecmf
                    state:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: locsx
                    country:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: fxfliskhtoupuvzsotgynjmac
                    zip:
                      type: string
                      description: 'Must not be greater than 50 characters.'
                      example: xixppwnthgherhrfpvwqic
                    address:
                      type: string
                      description: 'Must not be greater than 255 characters.'
                      example: uoqqttcvmqxxvqykwgdlazqmjrkujfpuhacwczmug
                    latitude:
                      type: number
                      description: ''
                      example: 46.93448851
                    longitude:
                      type: number
                      description: ''
                      example: 13807.772926074
                price:
                  type: object
                  description: ''
                  example: []
                  properties:
                    currency:
                      type: string
                      description: 'Must not be greater than 5 characters.'
                      example: bpita
                    price_per_day:
                      type: number
                      description: ''
                      example: 217626.6449587
                    per_day_minimum:
                      type: number
                      description: ''
                      example: 18840083.69
                    price_per_week:
                      type: number
                      description: ''
                      example: 205971.840459
                    price_per_hour:
                      type: number
                      description: ''
                      example: 202.9253306
                    per_hour_minimum:
                      type: number
                      description: ''
                      example: 9433263.0
                    price_per_night:
                      type: number
                      description: ''
                      example: 30107443.9
                    per_night_minimum:
                      type: number
                      description: ''
                      example: 0.0
                    security_allowance:
                      type: number
                      description: ''
                      example: 10366.519
                    price_per_multiple_days:
                      type: number
                      description: ''
                      example: 9298.952
                    per_multiple_days_minimum:
                      type: number
                      description: ''
                      example: 42.5076967
                    price_per_multiple_hours:
                      type: number
                      description: ''
                      example: 24.661
                    per_multiple_hours_minimum:
                      type: number
                      description: ''
                      example: 198.37
                    price_per_person:
                      type: number
                      description: ''
                      example: 5525.8501
                    per_person_charge_type:
                      type: number
                      description: ''
                      example: 81.54187284
                    cancellation_refund_rate:
                      type: number
                      description: ''
                      example: 2711125.6
                    cancellation_allowed_days:
                      type: number
                      description: ''
                      example: 23981107.615991
                    rental_terms:
                      type: number
                      description: ''
                      example: 540857717.81945
                publish:
                  type: boolean
                  description: ''
                  example: false
              required:
                - publish
      security: []
tags:
  -
    name: Endpoints
    description: ''
